version: "3.4"

services:
  mongo:
    container_name: venue_new_mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017
    logging:
      driver: none
    environment:
      - MONGO_INITDB_DATABASE=venue-new

  server:
    container_name: venue_new_server
    build: ./apollo-server
    command: ./node_modules/.bin/nodemon server
    restart: unless-stopped
    volumes:
      - ./apollo-server:/app
      - server_node_modules:/app/node_modules
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
      - JWTAUTH_KEY=${JWTAUTH_KEY}
      - DB_URL=mongodb://mongo:27017/venue-new
    depends_on:
      - mongo

  web:
    container_name: venue_new_web
    build: ./
    command: npm run serve
    restart: unless-stopped
    volumes:
      - ./:/app
      - web_node_modules:/app/node_modules
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - VUE_APP_GRAPHQL_HTTP=http://localhost:4000/graphql
      - VUE_APP_GRAPHQL_WS=ws://localhost:4000/graphql
    depends_on:
      - mongo
      - server

volumes:
  mongo_data:
  server_node_modules:
  web_node_modules:
