query courses {
  courses {
    id
    name
    prefix
    suffix
    start
    end
    auths {
      role
    }
    user_groups {
      id
      name
      auths {
        id
        role
      }
    }
    registration_sections {
      id
      name
      auths {
        id
        role
      }
      user_groups {
        id
        name
        auths {
          id
          role
        }
      }
    }
  }
}
