fragment Course on Course {
  _id
  name
  prefix
  suffix
  start
  end
  auths {
    role
  }
  user_groups {
    _id
    name
    auths {
      _id
      role
    }
  }
  registration_sections {
    _id
    name
    auths {
      _id
      role
    }
    user_groups {
      _id
      name
      auths {
        _id
        role
      }
    }
  }
}
