#import "./RegistrationSectionFrag.gql"

mutation createRegistrationSection($name: String!, $course: ID!) {
  createRegistrationSection(name: $name, course: $course) {
    ...RegistrationSection
  }
}
