#import "./CourseFrag.gql"

mutation createCourse(
  $name: String!
  $start: Date!
  $end: Date!
  $prefix: String
  $suffix: String
  $description: String
) {
  createCourse(name: $name, start: $start, end: $end, prefix: $prefix, suffix: $suffix, description: $description) {
    ...Course
  }
}
