#import "./RegistrationSectionFrag.gql"

mutation createRegistrationSection($name: String!, $parent_resource: ID) {
  createRegistrationSection(name: $name, parent_resource: $parent_resource) {
    ...RegistrationSection
  }
}
