query registrationSections {
  registrationSections {
    name
    parent_resource {
      id
      name
    }
    auths {
      id
      role
      user {
        id
        first_name
        last_name
      }
    }
  }
}
